/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                   'var(--color-primary)',
        'on-primary':                'var(--color-on-primary)',
        'primary-container':         'var(--color-primary-container)',
        'on-primary-container':      'var(--color-on-primary-container)',
        'secondary':                 'var(--color-secondary)',
        'on-secondary':              'var(--color-on-secondary)',
        'secondary-container':       'var(--color-secondary-container)',
        'on-secondary-container':    'var(--color-on-secondary-container)',
        'tertiary':                  'var(--color-tertiary)',
        'on-tertiary':               'var(--color-on-tertiary)',
        'tertiary-container':        'var(--color-tertiary-container)',
        'on-tertiary-container':     'var(--color-on-tertiary-container)',
        'surface':                   'var(--color-surface)',
        'on-surface':                'var(--color-on-surface)',
        'surface-variant':           'var(--color-surface-variant)',
        'on-surface-variant':        'var(--color-on-surface-variant)',
        'surface-container-lowest':  'var(--color-surface-container-lowest)',
        'surface-container-low':     'var(--color-surface-container-low)',
        'surface-container':         'var(--color-surface-container)',
        'surface-container-high':    'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'background':                'var(--color-background)',
        'on-background':             'var(--color-on-background)',
        'outline':                   'var(--color-outline)',
        'outline-variant':           'var(--color-outline-variant)',
        'error':                     'var(--color-error)',
        'on-error':                  'var(--color-on-error)',
        'error-container':           'var(--color-error-container)',
        'on-error-container':        'var(--color-on-error-container)',
        'inverse-surface':           'var(--color-inverse-surface)',
        'inverse-on-surface':        'var(--color-inverse-on-surface)',
        'inverse-primary':           'var(--color-inverse-primary)',
      },
      fontFamily: {
        headline: ['"Syne"', 'sans-serif'],
        body:     ['"DM Sans"', 'sans-serif'],
        label:    ['"DM Sans"', 'sans-serif'],
        mono:     ['"JetBrains Mono"', 'monospace'],
      },
    },
  },
  plugins: [],
}
