from __future__ import annotations

from copy import deepcopy

from operation_constants import (
    DOCX_IMAGE_TARGETS,
    HTML_TARGETS,
    IMAGE_TARGETS,
    IMAGE_TYPES,
    MARKDOWN_TARGETS,
    OCR_DOCUMENT_TARGETS,
    PDF_IMAGE_TARGETS,
    VIDEO_INPUT_TYPES,
    VIDEO_OUTPUT_FORMATS,
)
from operation_validation import ValidationResult, validate_params


# Canonical public capability catalog.
# Operations intentionally not exposed here:
# - PDF rotate backend edit
# - PPT/PPTX -> PDF
# - OCR, paid jobs, multi-file flows
OPERATIONS: dict[str, dict] = {
    "pdf_edit": {
        "intent": "edit",
        "kind": "client_editor",
        "input_types": ["pdf"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": "/editor/pdf",
        "requires_multiple": False,
        "params_schema": {},
        "category": "edit",
        "label": "Edit PDF",
    },
    "pdf_annotate": {
        "intent": "transform",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "watermark_type": {
                "type": "enum",
                "default": "text",
                "values": ["text", "image"],
                "label": "Watermark type",
            },
            "watermark_text": {"type": "string", "default": "DRAFT", "label": "Text"},
            "stamp_mode": {
                "type": "enum",
                "default": "watermark",
                "values": ["watermark", "header", "footer", "corner"],
                "label": "Placement",
            },
            "opacity": {"type": "float", "default": 0.3, "minimum": 0.05, "maximum": 1, "label": "Opacity"},
        },
        "category": "pdf",
        "label": "Add PDF watermark",
        "lambda_suffix": "pdf-annotate",
    },
    "pdf_merge": {
        "intent": "transform",
        "kind": "backend_job",
        "input_types": ["zip"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": True,
        "params_schema": {},
        "category": "pdf",
        "label": "Merge PDFs",
        "lambda_suffix": "pdf-merge",
    },
    "pdf_split": {
        "intent": "transform",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "zip",
        "targets": ["zip"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "ranges": {"type": "string", "default": "", "label": "Page ranges"},
        },
        "category": "pdf",
        "label": "Split PDF",
        "lambda_suffix": "pdf-split",
    },
    "pdf_compress": {
        "intent": "transform",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "pdf",
        "label": "Compress PDF",
        "lambda_suffix": "pdf-compress",
    },
    "pdf_rearrange": {
        "intent": "transform",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "page_order": {"type": "string", "default": "", "label": "Page order"},
        },
        "category": "pdf",
        "label": "Rearrange PDF pages",
        "lambda_suffix": "pdf-rearrange",
    },
    "pdf_svg_annotate": {
        "intent": "transform",
        "kind": "backend_job",
        "input_types": ["zip"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "flatten": {"type": "boolean", "default": False, "label": "Flatten annotations"},
        },
        "category": "pdf",
        "label": "Apply SVG annotations",
        "lambda_suffix": "pdf-svg-annotate",
    },
    "pdf_remove_watermark": {
        "intent": "transform",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "watermark_text": {"type": "string", "default": "", "label": "Watermark text"},
            "dry_run": {"type": "boolean", "default": False, "label": "Dry run report"},
            "confidence_min": {"type": "float", "default": 0.6, "minimum": 0.3, "maximum": 1, "label": "Minimum confidence"},
            "case": {
                "type": "enum",
                "default": "auto",
                "values": ["auto", "annot", "xobject"],
                "label": "Detection mode",
            },
        },
        "category": "pdf",
        "label": "Remove PDF watermark",
        "lambda_suffix": "pdf-remove-watermark",
    },
    "doc_edit": {
        "intent": "edit",
        "kind": "client_editor",
        "input_types": ["docx"],
        "output_type": "docx",
        "targets": ["docx"],
        "editor_route": "/editor/docx",
        "requires_multiple": False,
        "params_schema": {},
        "category": "edit",
        "label": "Edit Word document",
    },
    "md_edit": {
        "intent": "edit",
        "kind": "client_editor",
        "input_types": ["md", "markdown", "txt"],
        "output_type": "md",
        "targets": ["md"],
        "editor_route": "/editor/markdown",
        "requires_multiple": False,
        "params_schema": {},
        "category": "edit",
        "label": "Edit Markdown",
    },
    "xlsx_edit": {
        "intent": "edit",
        "kind": "client_editor",
        "input_types": ["xlsx"],
        "output_type": "xlsx",
        "targets": ["xlsx"],
        "editor_route": "/editor/xlsx",
        "requires_multiple": False,
        "params_schema": {},
        "category": "edit",
        "label": "Edit spreadsheet",
    },
    "image_edit": {
        "intent": "edit",
        "kind": "client_editor",
        "input_types": IMAGE_TYPES,
        "output_type": "same",
        "targets": IMAGE_TYPES,
        "editor_route": "/editor/image",
        "requires_multiple": False,
        "params_schema": {},
        "category": "edit",
        "label": "Edit image",
    },
    "pdf_to_docx": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "docx",
        "targets": ["docx"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "high_fidelity": {
                "type": "boolean",
                "required": False,
                "default": False,
                "label": "High fidelity",
            },
            "fallback_strategy": {
                "type": "enum",
                "required": False,
                "default": "text",
                "values": ["text", "image"],
                "label": "If it doesn't work, try converting the document to:",
            },
            "page_range": {
                "type": "string",
                "required": False,
                "default": "",
                "label": "Page range (e.g. 1-10, 3, 5-8)",
            },
        },
        "category": "convert",
        "label": "PDF to Word (.docx)",
        "lambda_suffix": "pdf-to-docx",
    },
    "pdf_to_xls": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "xlsx",
        "targets": ["xlsx"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "convert",
        "label": "PDF to Excel (.xlsx)",
        "lambda_suffix": "pdf-to-xls",
    },
    "pdf_to_txt": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "txt",
        "targets": ["txt"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "convert",
        "label": "PDF to Text (.txt)",
        "lambda_suffix": "pdf-to-txt",
    },
    "pdf_to_md": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "md",
        "targets": ["md"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "convert",
        "label": "PDF to Markdown (.md)",
        "lambda_suffix": "pdf-to-txt",
    },
    "pdf_to_html": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "html",
        "targets": ["html"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "convert",
        "label": "PDF to HTML",
        "lambda_suffix": "pdf-to-txt",
    },
    "pdf_to_image": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "zip",
        "targets": PDF_IMAGE_TARGETS,
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "dpi": {
                "type": "integer",
                "default": 150,
                "minimum": 72,
                "maximum": 300,
            },
            "target_format": {
                "type": "string",
                "required": True,
                "enum": PDF_IMAGE_TARGETS,
                "default": "png",
            },
        },
        "category": "convert",
        "label": "PDF to PNG images (.zip)",
        "lambda_suffix": "pdf-to-image",
    },
    "image_to_pdf": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": IMAGE_TYPES,
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "convert",
        "label": "Image to PDF",
        "lambda_suffix": "image-to-pdf",
    },
    "image_convert": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": IMAGE_TYPES,
        "output_type": "image",
        "targets": IMAGE_TARGETS,
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "target_format": {
                "type": "string",
                "required": True,
                "enum": IMAGE_TARGETS,
            }
        },
        "category": "convert",
        "label": "Convert image format",
        "lambda_suffix": "image-convert",
    },
    "image_to_document": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["png", "jpg", "jpeg"],
        "output_type": "document",
        "targets": OCR_DOCUMENT_TARGETS,
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "target_format": {
                "type": "string",
                "required": True,
                "enum": OCR_DOCUMENT_TARGETS,
            }
        },
        "category": "convert",
        "label": "Image OCR",
        "lambda_suffix": "image-convert",
    },
    "markdown_convert": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["md", "markdown", "txt"],
        "output_type": "document",
        "targets": MARKDOWN_TARGETS,
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "target_format": {
                "type": "string",
                "required": True,
                "enum": MARKDOWN_TARGETS,
            }
        },
        "category": "convert",
        "label": "Convert Markdown",
        "lambda_suffix": "markdown-convert",
    },
    "docx_to_txt": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["docx"],
        "output_type": "txt",
        "targets": ["txt"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "convert",
        "label": "Word to Text (.txt)",
        "lambda_suffix": "docx-to-txt",
    },
    "docx_to_md": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["docx"],
        "output_type": "md",
        "targets": ["md"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "convert",
        "label": "Word to Markdown (.md)",
        "lambda_suffix": "docx-to-txt",
    },
    "docx_to_html": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["docx"],
        "output_type": "html",
        "targets": ["html"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "convert",
        "label": "Word to HTML",
        "lambda_suffix": "docx-to-txt",
    },
    "docx_to_pdf": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["docx"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "paper_size": {
                "type": "string",
                "required": False,
                "enum": ["A4", "A3", "Letter", "Legal", "A5"],
                "default": "A4",
            },
            "high_fidelity": {
                "type": "boolean",
                "required": False,
                "default": True,
                "label": "High fidelity (LibreOffice)",
            },
        },
        "category": "convert",
        "label": "Word to PDF",
        "lambda_suffix": "docx-to-pdf",
    },
    "docx_to_image": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["docx"],
        "output_type": "zip",
        "targets": DOCX_IMAGE_TARGETS,
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "paper_size": {
                "type": "string",
                "required": False,
                "enum": ["A4", "A3", "Letter", "Legal", "A5"],
                "default": "A4",
            },
            "dpi": {
                "type": "integer",
                "default": 150,
                "minimum": 72,
                "maximum": 300,
            },
            "target_format": {
                "type": "string",
                "required": True,
                "enum": DOCX_IMAGE_TARGETS,
                "default": "png",
            },
        },
        "category": "convert",
        "label": "Word to images (.zip)",
        "lambda_suffix": "docx-to-pdf",
    },
    "xlsx_to_md": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["xlsx"],
        "output_type": "md",
        "targets": ["md"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "sheet": {
                "type": "string",
                "required": False,
                "maxLength": 64,
                "default": "",
            }
        },
        "category": "convert",
        "label": "Excel to Markdown (.md)",
        "lambda_suffix": "xlsx-to-csv",
    },
    "xlsx_to_txt": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["xlsx"],
        "output_type": "txt",
        "targets": ["txt"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "sheet": {
                "type": "string",
                "required": False,
                "maxLength": 64,
                "default": "",
            }
        },
        "category": "convert",
        "label": "Excel to Text (.txt)",
        "lambda_suffix": "xlsx-to-csv",
    },
    "xlsx_to_html": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["xlsx"],
        "output_type": "html",
        "targets": ["html"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "sheet": {
                "type": "string",
                "required": False,
                "maxLength": 64,
                "default": "",
            }
        },
        "category": "convert",
        "label": "Excel to HTML",
        "lambda_suffix": "xlsx-to-csv",
    },
    "xlsx_to_csv": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["xlsx"],
        "output_type": "csv",
        "targets": ["csv"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "sheet": {
                "type": "string",
                "required": False,
                "maxLength": 64,
                "default": "",
            }
        },
        "category": "convert",
        "label": "Excel to CSV (first sheet)",
        "lambda_suffix": "xlsx-to-csv",
    },
    "xlsx_to_pdf": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["xlsx", "xls"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "sheet": {
                "type": "string",
                "required": False,
                "maxLength": 64,
                "default": "",
            },
            "paper_size": {
                "type": "string",
                "required": False,
                "enum": ["A4", "A3", "Letter", "Legal", "A5"],
                "default": "A4",
            },
            "high_fidelity": {
                "type": "boolean",
                "required": False,
                "default": True,
                "label": "High fidelity (LibreOffice)",
            },
        },
        "category": "convert",
        "label": "Excel to PDF",
        "lambda_suffix": "xlsx-to-pdf",
    },
    "xlsx_to_docx": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["xlsx"],
        "output_type": "docx",
        "targets": ["docx"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "sheet": {
                "type": "string",
                "required": False,
                "maxLength": 64,
                "default": "",
            }
        },
        "category": "convert",
        "label": "Excel to Word (.docx)",
        "lambda_suffix": "xlsx-to-pdf",
    },
    "xlsx_to_image": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["xlsx"],
        "output_type": "zip",
        "targets": PDF_IMAGE_TARGETS,
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "sheet": {
                "type": "string",
                "required": False,
                "maxLength": 64,
                "default": "",
            },
            "paper_size": {
                "type": "string",
                "required": False,
                "enum": ["A4", "A3", "Letter", "Legal", "A5"],
                "default": "A4",
            },
            "dpi": {
                "type": "integer",
                "default": 150,
                "minimum": 72,
                "maximum": 300,
            },
            "target_format": {
                "type": "string",
                "required": True,
                "enum": PDF_IMAGE_TARGETS,
                "default": "png",
            },
        },
        "category": "convert",
        "label": "Excel to PNG images (.zip)",
        "lambda_suffix": "xlsx-to-pdf",
    },
    "html_convert": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": ["html", "htm"],
        "output_type": "document",
        "targets": HTML_TARGETS,
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "target_format": {
                "type": "string",
                "required": True,
                "enum": HTML_TARGETS,
                "default": "txt",
            }
        },
        "category": "convert",
        "label": "Convert HTML",
        "lambda_suffix": "html-convert",
    },
    "video_process": {
        "intent": "convert",
        "kind": "backend_job",
        "input_types": VIDEO_INPUT_TYPES,
        "output_type": "multi",
        "targets": VIDEO_OUTPUT_FORMATS,
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {},
        "category": "video",
        "label": "Process video",
        "lambda_suffix": "video-process",
    },
    "pdf_make_editable": {
        "intent": "transform",
        "kind": "backend_job",
        "input_types": ["pdf"],
        "output_type": "pdf",
        "targets": ["pdf"],
        "editor_route": None,
        "requires_multiple": False,
        "params_schema": {
            "language": {
                "type": "enum",
                "default": "eng+por",
                "label": "OCR language",
                "values": ["eng+por", "eng", "por"],
                "labels": {
                    "eng+por": "English + Portuguese",
                    "eng": "English",
                    "por": "Portuguese",
                },
            },
        },
        "category": "pdf",
        "label": "Make PDF Editable",
        "lambda_suffix": "pdf-make-editable",
    },
}


OPERATION_FUNCTION_SUFFIX: dict[str, str] = {}
for _op, _meta in OPERATIONS.items():
    if _meta["kind"] in ("backend_job", "paid_backend_job"):
        OPERATION_FUNCTION_SUFFIX[_op] = _meta["lambda_suffix"]

# Operations that have a fast pure-Python Lambda variant (-fast suffix).
# When params.high_fidelity is explicitly False the dispatcher routes there.
HAS_FAST_VARIANT: frozenset[str] = frozenset({"docx_to_pdf", "xlsx_to_pdf", "pdf_to_docx"})


def is_supported(operation: str) -> bool:
    """Return whether operation is a known public operation id."""
    return operation in OPERATIONS


def list_operations(input_type: str | None = None) -> list[dict]:
    """Return the public-facing catalog, optionally filtered by input type."""
    ext = None
    if input_type is not None:
        ext = input_type.lower().lstrip(".")

    results: list[dict] = []
    for op, meta in OPERATIONS.items():
        if ext is not None and ext not in meta["input_types"]:
            continue
        results.append({
            "operation": op,
            "intent": meta["intent"],
            "kind": meta["kind"],
            "label": meta["label"],
            "category": meta["category"],
            "input_types": list(meta["input_types"]),
            "output_type": meta["output_type"],
            "targets": list(meta["targets"]),
            "editor_route": meta.get("editor_route"),
            "requires_multiple": bool(meta.get("requires_multiple", False)),
            "params_schema": deepcopy(meta.get("params_schema", {})),
        })
    return results
